# Generated by Django 4.0.1 on 2022-01-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='mentor',
            name='FirstName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='LastName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='FirstName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='LastName',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
