# Generated by Django 4.0.1 on 2022-01-21 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_schedule_rename_firstname_mentor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.mentor'),
        ),
    ]
