# Generated by Django 4.0.1 on 2022-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_student_schedule_schedule_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subject_name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
