# Generated by Django 4.0.1 on 2022-01-21 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_mentor_id_appointment_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.mentor')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
