# Generated by Django 4.0.1 on 2022-01-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_subject_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='subject_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.subject'),
        ),
    ]
