# Generated by Django 4.0.1 on 2022-01-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_subject_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Starting Time'),
        ),
    ]
