# Generated by Django 4.0.1 on 2022-01-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_appointment_end_time_appointment_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation',
            field=models.BooleanField(null=True),
        ),
    ]
