# Generated by Django 4.0.1 on 2022-01-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_schedule_service_servicebooked_serviceprovided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.TimeField(),
        ),
    ]
