# Generated by Django 4.0.1 on 2022-01-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_service_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='estimated_time',
        ),
    ]
