# Generated by Django 4.0.1 on 2022-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_alter_schedule_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_mentor',
            field=models.BooleanField(null=True),
        ),
    ]
