# Generated by Django 4.0.1 on 2022-01-22 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0016_remove_mentor_first_name_remove_mentor_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
