# Generated by Django 4.0.1 on 2022-01-22 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
