# Generated by Django 4.0.1 on 2022-01-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_remove_appointment_schedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
