# Generated by Django 4.0.1 on 2022-01-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='student_id',
        ),
    ]
