# Generated by Django 4.0.1 on 2022-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_appointment_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooked',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
