# Generated by Django 4.0.1 on 2022-01-26 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_servicebooked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooked',
            name='appointment_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='servicebooked_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.servicebooked'),
        ),
    ]
