# Generated by Django 4.0.1 on 2022-01-26 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0027_remove_servicebooked_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='servicebooked_id',
        ),
        migrations.AddField(
            model_name='servicebooked',
            name='appointment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
    ]
